package frontend;

import backend.HuffmanNode;

public class ConsolePrinter {
    /**
     * Print sign dictionary
     * @param root root huffman tree node
     * @param s sign code (recursion)
     */
    public static void printCode(HuffmanNode root, String s) {
        // base case; if the left and right are null
        // then its a leaf node and we print
        // the code s generated by traversing the tree.
        if (root.getLeft() == null && root.getRight() == null) {

            System.out.println(root.getSign() + ":" + s);
            return;
        }

        // if we go to left then add "0" to the code.
        // if we go to the right add "1" to the code.

        // recursive calls for left and
        // right sub-tree of the generated tree.
        printCode(root.getLeft(), s + "0");
        printCode(root.getRight(), s + "1");
    }
}
